# Properties file with JDBC and JPA settings.
jdbc.initLocation=classpath:db/mysql/schema.sql
jdbc.dataLocation=classpath:db/mysql/data.sql
jdbc.initEnable=false

jpa.showSql=true

jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=${jdbc.url:jdbc:mysql://${DB_HOST:vetcore-private-db-rds-mysql.czgliwfs2orh.ap-northeast-2.rds.amazonaws.com}:3306/petclinic?useUnicode=true}
jdbc.username=${jdbc.username:${DB_USER:petclinic}}
jdbc.password=${jdbc.password:${DB_PASSWORD:}}

jpa.database=MYSQL
